[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; Port USB ESP32 CP2102 yang terdeteksi
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

build_flags =
    -DBOARD_HAS_PSRAM
